Added ability to include NRPT records to NameServers list automatical…
MichaCo/DnsClient.NET pull request #114
Opened 2021-05-16 20:42 UTC by SteveSyfuhs

…ly on Windows

2021-05-16 22:17 UTC, MichaCo requested changes
Looks pretty good overall, but I think we can simplify it by removing the configuration flags / options.

2021-05-16 22:17 UTC, MichaCo commented on src/DnsClient/DnsQueryOptions.cs
> +        public bool UseNameResolutionPolicyTable { get; set; } = true;
I'm not sure we really have to introduce another configuration point for this.
The current auto resolve mechanism does its best getting all kind of information already and most systems probably don't even have those policies, so I guess we could just always check for that?

Would also make my life easier with the constructor change of NameServer. 
That would be kind of a breaking change if we introduce another optional parameter -.-

2021-05-16 22:17 UTC, MichaCo commented on src/DnsClient/Interop/Windows/NameResolutionPolicy.cs
> +                    var policyKey = OpenPreferredKey(policyGuid, policyRoot, parametersRoot);
Doesn't seem to be reused, I'd rather inline that

2021-05-16 22:17 UTC, MichaCo commented on src/DnsClient/Interop/Windows/NameResolutionPolicy.cs
> +                        policyKey.Dispose();
use `using (policyKey);` instead?

2021-05-16 22:17 UTC, MichaCo commented on src/DnsClient/Interop/Windows/NameResolutionPolicy.cs
> +                    foreach (var name in names.Where(n => n.StartsWith(".")).Distinct())
names might need a null check earlier

2021-05-16 22:17 UTC, MichaCo commented on src/DnsClient/NameServer.cs
> +            DnsSuffix = string.IsNullOrWhiteSpace(dnsSuffix) ? null : dnsSuffix;
Ups, good catch, actually an error I added yesterday.
Could you change the ctor above, too, and pass dnsSuffix through instead of setting it there?

2021-05-16 22:17 UTC, MichaCo commented on src/DnsClient/NameServer.cs
> +                    if (nprt.Any())
:nit: always use property `.Length != 0` instead of Any

2021-05-17 16:22 UTC, MichaCo commented
I actually didn't know about that new rule in .NET5
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416

Or those new attributes... Seems fancy
The new construct `OperatingSystem` only exists in .NET5 which means we cannot use it anyways.
I think you can safely disable the rule in .editorconfig

2021-05-17 16:24 UTC, MichaCo commented
never mind, you fixed it already ;)

2021-05-17 16:28 UTC, SteveSyfuhs commented
Yeah, this rule is new to me too. Was easy enough to fix though.

2021-05-17 21:47 UTC, MichaCo approved these changes
Looks good, I tested it also locally on Windows and Linux, seems all fine.

Thanks a lot again for the contribution @SteveSyfuhs !

2021-05-17 21:48 UTC, merged