PR for Duplicated UDP responses from DNS confuse LookupClient #140
MichaCo/DnsClient.NET pull request #142
Opened 2022-01-18 21:35 UTC by JamesKovacs

The following PR is to resolve the issue reported in #140.

2022-01-23 12:59 UTC, MichaCo commented
Hi @JamesKovacs 
I think the implementation itself looks reasonable (will review it a bit more now)

The unit test, especially `Lookup_XidMismatch` seems a bit flaky though: The 2 tests with `mismatchResponses` = 10 fail for me locally all the time.

2022-01-23 14:26 UTC, MichaCo requested changes
Looks good overall. Just 2 minor things

2022-01-23 14:26 UTC, MichaCo commented on test/DnsClient.Tests/LookupTest.cs
> +        [InlineData(10, false)]
```suggestion
        //[InlineData(10, false)]
```

2022-01-23 14:26 UTC, MichaCo commented on test/DnsClient.Tests/LookupTest.cs
> +        [InlineData(10, true)]
```suggestion
        //[InlineData(10, true)]
```

Not sure why those 2 variants fail, at least when run under .NET47x. 
Let's just comment it out for now?

2022-01-23 14:26 UTC, MichaCo commented on src/DnsClient/DnsMessageHandler.cs
> +            if (request.Header.Id != response.Header.Id)
right now, response can be potentially be null at this point, at least if the TCP handler is used.
I'll change that in another PR.
But maybe better do a null check and return right away, if response or request are null.

2022-01-25 23:50 UTC, JamesKovacs commented
Thanks for the feedback. I've addressed your comments and will push another commit to the branch shortly.

2022-01-26 16:31 UTC, JamesKovacs commented
Changes pushed and ready for review. Thanks again!

2022-01-26 20:14 UTC, MichaCo approved these changes

2022-01-26 20:14 UTC, merged

2022-01-26 20:16 UTC, MichaCo commented
The tests failed during build. I'll fix that later, seems not really related to your changes.
I have to finish one more change and then planning to release this end of the week I think.

Thanks again for your help!

2022-01-30 03:57 UTC, djj0809 commented
@MichaCo Looking forward to the new version. 

We have been seeing DNS resolution failure in one of our cluster from time to time but was not able to identity the root cause, thanks @JamesKovacs !